name: Build and Publish NuGet

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        efcore_version: [8, 9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Build the project
        run: |
          dotnet build -p:EFCORE_VERSION=${{ matrix.efcore_version }} -c Release
          
      - name: Pack the NuGet package
        run: |
          dotnet pack -p:EFCORE_VERSION=${{ matrix.efcore_version }} -c Release -o ./nupkgs

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
